=== davidjeck/javanotes9/javanotes8/javanotes8.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY pi "&#960;">       <!-- these are used by javanotes7.xml but are redefined in javanotes7-tex.xml -->
<!ENTITY Omega "&#937;">
<!ENTITY Theta "&#920;">
<!ENTITY nbsp "&#160;">
<!ENTITY BigOh "O">
<!ENTITY dots "...">
<!ENTITY mdash " -- ">
<!ENTITY leftquote '"'>
<!ENTITY textitlebreak "">
<!ENTITY newcodestyle "red">

<!ENTITY includes SYSTEM "javanotes8-xml-includes.txt">

<!ENTITY % textitem "b|i|u|big|sub|sup|code|br|a|localref|web|tex|sourceref|jarref|ptype|newword|codedef|bnf|newcode|start|classname|atype|prog">
<!ENTITY % simpletext "(#PCDATA|%textitem;)*">
<!ENTITY % text "(p|np|pre|break|img|ul|ol|narrower|centered|imageclear|webdiv|texdiv)*">

<!ELEMENT javanotes (preface?,chapter*,fudgeref*,glossary?,source?)>
<!ELEMENT preface (%text;)>
<!ELEMENT intro (%text;)>

<!ELEMENT chapter (intro,section*,exercises?,quiz?)>
<!ATTLIST chapter 
	id ID #REQUIRED
	title CDATA #REQUIRED
	shorttitle CDATA #IMPLIED>

<!ELEMENT section (%text;,subsection*,endchapter?)>
<!ATTLIST section 
	id ID #REQUIRED
	title CDATA #REQUIRED
	shorttitle CDATA #IMPLIED>

<!ELEMENT subsection (%text;)>
<!ATTLIST subsection 
	id ID #REQUIRED
	title CDATA #REQUIRED
	shorttitle CDATA #IMPLIED>
<!ELEMENT endchapter EMPTY>

<!ELEMENT source (%text;,subsection*)>

<!ELEMENT glossary (gitem*)>
<!ELEMENT gitem %simpletext;>
<!ATTLIST gitem
   term CDATA #REQUIRED>

<!ELEMENT fudgeref EMPTY>
<!ATTLIST fudgeref
   id ID #REQUIRED
   text CDATA #REQUIRED>

<!ELEMENT exercises (exercise*)>
<!ELEMENT exercise (exercise-question,exercise-discuss,exercise-code)>
<!ATTLIST exercise
    id ID #IMPLIED>
<!ELEMENT exercise-question %text;>
<!ELEMENT exercise-discuss %text;>
<!ELEMENT exercise-code %text;>

<!ELEMENT quiz (question*)>
<!ELEMENT question (ques,ans)>
<!ELEMENT ques %text;>
<!ELEMENT ans %text;>

<!ELEMENT pre %simpletext;>
<!ATTLIST pre
	xml:space CDATA #FIXED "preserve">
	
<!ELEMENT prog %simpletext;>
<!ATTLIST prog
	xml:space CDATA #FIXED "preserve"
	name CDATA #REQUIRED>

<!ELEMENT p %simpletext;>
<!ATTLIST p 
    align CDATA #IMPLIED>
<!ELEMENT np %simpletext;>

<!ELEMENT narrower %text;>
<!ATTLIST narrower
   margin CDATA #IMPLIED>

<!ELEMENT centered %text;>

<!ELEMENT localref (#PCDATA)>
<!ATTLIST localref
    href CDATA #REQUIRED>

<!ELEMENT sourceref (#PCDATA)>
<!ATTLIST sourceref
    href CDATA #REQUIRED
    chapter CDATA #IMPLIED>

<!ELEMENT jarref (#PCDATA)>
<!ATTLIST jarref
    href CDATA #REQUIRED>

<!ELEMENT a (#PCDATA)>
<!ATTLIST a
    href CDATA #REQUIRED>

<!ELEMENT img EMPTY>
<!ATTLIST img
    src CDATA #IMPLIED
    alt CDATA #IMPLIED
    width CDATA #IMPLIED
    height CDATA #IMPLIED
    bordered CDATA #IMPLIED
    align CDATA #IMPLIED
    tex CDATA #IMPLIED
    texscale CDATA #IMPLIED>
    
<!ELEMENT ul (li*)>
<!ELEMENT ol (li*)>
<!ELEMENT li %simpletext;>

<!ELEMENT br EMPTY>
<!ELEMENT break EMPTY>
<!ELEMENT imageclear EMPTY> <!-- adds a "br clear=all" in the web version -->
<!ELEMENT i %simpletext;>
<!ELEMENT b %simpletext;>
<!ELEMENT u %simpletext;>
<!ELEMENT big %simpletext;>
<!ELEMENT start %simpletext;>
<!ELEMENT sup %simpletext;>
<!ELEMENT sub %simpletext;>
<!ELEMENT code %simpletext;>
<!ELEMENT newcode %simpletext;>
<!ELEMENT web %simpletext;>   <!-- appears only in web version -->
<!ELEMENT tex %simpletext;>   <!-- appears only in tex version -->
<!ELEMENT ptype %simpletext;>   <!-- primitive type -->
<!ELEMENT bnf %simpletext;>
<!ELEMENT classname (#PCDATA)>
<!ELEMENT atype (#PCDATA)>       <!-- array type -->
<!ELEMENT newword %simpletext;>
<!ELEMENT codedef %simpletext;>
<!ELEMENT webdiv %text;>   <!-- appears only in web version -->
<!ELEMENT texdiv %text;>   <!-- appears only in tex version -->

<!ENTITY source SYSTEM "source.xml">
<!ENTITY glossary SYSTEM "glossary.xml">
<!ENTITY preface SYSTEM "preface.xml">

<!ENTITY overview_intro SYSTEM "c1-overview/intro.xml">
<!ENTITY overview_s1 SYSTEM "c1-overview/s1.xml">
<!ENTITY overview_s2 SYSTEM "c1-overview/s2.xml">
<!ENTITY overview_s3 SYSTEM "c1-overview/s3.xml">
<!ENTITY overview_s4 SYSTEM "c1-overview/s4.xml">
<!ENTITY overview_s5 SYSTEM "c1-overview/s5.xml">
<!ENTITY overview_s6 SYSTEM "c1-overview/s6.xml">
<!ENTITY overview_s7 SYSTEM "c1-overview/s7.xml">
<!ENTITY overview_quiz SYSTEM "c1-overview/quiz.xml">

<!ENTITY basics_intro SYSTEM "c2-basics/intro.xml">
<!ENTITY basics_s1 SYSTEM "c2-basics/s1.xml">
<!ENTITY basics_s2 SYSTEM "c2-basics/s2.xml">
<!ENTITY basics_s3 SYSTEM "c2-basics/s3.xml">
<!ENTITY basics_s4 SYSTEM "c2-basics/s4.xml">
<!ENTITY basics_s5 SYSTEM "c2-basics/s5.xml">
<!ENTITY basics_s6 SYSTEM "c2-basics/s6.xml">
<!ENTITY basics_exercises SYSTEM "c2-basics/exercises.xml">
<!ENTITY basics_quiz SYSTEM "c2-basics/quiz.xml">

<!ENTITY control_intro SYSTEM "c3-control/intro.xml">
<!ENTITY control_s1 SYSTEM "c3-control/s1.xml">
<!ENTITY control_s2 SYSTEM "c3-control/s2.xml">
<!ENTITY control_s3 SYSTEM "c3-control/s3.xml">
<!ENTITY control_s4 SYSTEM "c3-control/s4.xml">
<!ENTITY control_s5 SYSTEM "c3-control/s5.xml">
<!ENTITY control_s6 SYSTEM "c3-control/s6.xml">
<!ENTITY control_s7 SYSTEM "c3-control/s7.xml">
<!ENTITY control_s7a SYSTEM "c3-control/s7a.xml">
<!ENTITY control_s8 SYSTEM "c3-control/s8.xml">
<!ENTITY control_exercises SYSTEM "c3-control/exercises.xml">
<!ENTITY control_quiz SYSTEM "c3-control/quiz.xml">

<!ENTITY subroutines_intro SYSTEM "c4-subroutines/intro.xml">
<!ENTITY subroutines_s1 SYSTEM "c4-subroutines/s1.xml">
<!ENTITY subroutines_s2 SYSTEM "c4-subroutines/s2.xml">
<!ENTITY subroutines_s3 SYSTEM "c4-subroutines/s3.xml">
<!ENTITY subroutines_s4 SYSTEM "c4-subroutines/s4.xml">
<!ENTITY subroutines_s4a SYSTEM "c4-subroutines/s4a.xml">
<!ENTITY subroutines_s5 SYSTEM "c4-subroutines/s5.xml">
<!ENTITY subroutines_s6 SYSTEM "c4-subroutines/s6.xml">
<!ENTITY subroutines_s7 SYSTEM "c4-subroutines/s7.xml">
<!ENTITY subroutines_exercises SYSTEM "c4-subroutines/exercises.xml">
<!ENTITY subroutines_quiz SYSTEM "c4-subroutines/quiz.xml">

<!ENTITY OOP_intro SYSTEM "c5-OOP/intro.xml">
<!ENTITY OOP_s1 SYSTEM "c5-OOP/s1.xml">
<!ENTITY OOP_s2 SYSTEM "c5-OOP/s2.xml">
<!ENTITY OOP_s3 SYSTEM "c5-OOP/s3.xml">
<!ENTITY OOP_s4 SYSTEM "c5-OOP/s4.xml">
<!ENTITY OOP_s5 SYSTEM "c5-OOP/s5.xml">
<!ENTITY OOP_s6 SYSTEM "c5-OOP/s6.xml">
<!ENTITY OOP_s7 SYSTEM "c5-OOP/s7.xml">
<!ENTITY OOP_s8 SYSTEM "c5-OOP/s8.xml">
<!ENTITY OOP_exercises SYSTEM "c5-OOP/exercises.xml">
<!ENTITY OOP_quiz SYSTEM "c5-OOP/quiz.xml">

<!ENTITY GUI1_intro SYSTEM "c6-GUI1/intro.xml">
<!ENTITY GUI1_s1 SYSTEM "c6-GUI1/s1.xml"> 
<!ENTITY GUI1_s2 SYSTEM "c6-GUI1/s2.xml"> 
<!ENTITY GUI1_s3 SYSTEM "c6-GUI1/s3.xml">
<!ENTITY GUI1_s4 SYSTEM "c6-GUI1/s4.xml">
<!ENTITY GUI1_s5 SYSTEM "c6-GUI1/s5.xml">
<!ENTITY GUI1_s6 SYSTEM "c6-GUI1/s6.xml">
<!ENTITY GUI1_exercises SYSTEM "c6-GUI1/exercises.xml">
<!ENTITY GUI1_quiz SYSTEM "c6-GUI1/quiz.xml">

<!ENTITY arrays_intro SYSTEM "c7-arrays/intro.xml">
<!ENTITY arrays_s1 SYSTEM "c7-arrays/s1.xml">
<!ENTITY arrays_s2 SYSTEM "c7-arrays/s2.xml">
<!ENTITY arrays_s3 SYSTEM "c7-arrays/s3.xml">
<!ENTITY arrays_s4 SYSTEM "c7-arrays/s4.xml">
<!ENTITY arrays_s5 SYSTEM "c7-arrays/s5.xml">
<!ENTITY arrays_exercises SYSTEM "c7-arrays/exercises.xml">
<!ENTITY arrays_quiz SYSTEM "c7-arrays/quiz.xml">

<!ENTITY robustness_intro SYSTEM "c8-robustness/intro.xml">
<!ENTITY robustness_s1 SYSTEM "c8-robustness/s1.xml">
<!ENTITY robustness_s2 SYSTEM "c8-robustness/s2.xml">
<!ENTITY robustness_s3 SYSTEM "c8-robustness/s3.xml">
<!ENTITY robustness_s4 SYSTEM "c8-robustness/s4.xml">
<!ENTITY robustness_s5 SYSTEM "c8-robustness/s5.xml">
<!ENTITY robustness_exercises SYSTEM "c8-robustness/exercises.xml">
<!ENTITY robustness_quiz SYSTEM "c8-robustness/quiz.xml">

<!ENTITY recursion_intro SYSTEM "c9-recursion/intro.xml">
<!ENTITY recursion_s1 SYSTEM "c9-recursion/s1.xml">
<!ENTITY recursion_s2 SYSTEM "c9-recursion/s2.xml">
<!ENTITY recursion_s3 SYSTEM "c9-recursion/s3.xml">
<!ENTITY recursion_s4 SYSTEM "c9-recursion/s4.xml">
<!ENTITY recursion_s5 SYSTEM "c9-recursion/s5.xml">
<!ENTITY recursion_exercises SYSTEM "c9-recursion/exercises.xml">
<!ENTITY recursion_quiz SYSTEM "c9-recursion/quiz.xml">

<!ENTITY generics_intro SYSTEM "c10-generics/intro.xml">
<!ENTITY generics_s1 SYSTEM "c10-generics/s1.xml">
<!ENTITY generics_s2 SYSTEM "c10-generics/s2.xml">
<!ENTITY generics_s3 SYSTEM "c10-generics/s3.xml">
<!ENTITY generics_s4 SYSTEM "c10-generics/s4.xml">
<!ENTITY generics_s5 SYSTEM "c10-generics/s5.xml">
<!ENTITY generics_s6 SYSTEM "c10-generics/s6.xml">
<!ENTITY generics_exercises SYSTEM "c10-generics/exercises.xml">
<!ENTITY generics_quiz SYSTEM "c10-generics/quiz.xml">

<!ENTITY IO_intro SYSTEM "c11-IO/intro.xml">
<!ENTITY IO_s1 SYSTEM "c11-IO/s1.xml">
<!ENTITY IO_s2 SYSTEM "c11-IO/s2.xml">
<!ENTITY IO_s3 SYSTEM "c11-IO/s3.xml">
<!ENTITY IO_s4 SYSTEM "c11-IO/s4.xml">
<!ENTITY IO_s5 SYSTEM "c11-IO/s5.xml">
<!ENTITY IO_exercises SYSTEM "c11-IO/exercises.xml">
<!ENTITY IO_quiz SYSTEM "c11-IO/quiz.xml">

<!ENTITY threads_intro SYSTEM "c12-threads/intro.xml">
<!ENTITY threads_s1 SYSTEM "c12-threads/s1.xml">
<!ENTITY threads_s2 SYSTEM "c12-threads/s2.xml">
<!ENTITY threads_s3 SYSTEM "c12-threads/s3.xml">
<!ENTITY threads_s4 SYSTEM "c12-threads/s4.xml">
<!ENTITY threads_s5 SYSTEM "c12-threads/s5.xml">
<!ENTITY threads_exercises SYSTEM "c12-threads/exercises.xml">
<!ENTITY threads_quiz SYSTEM "c12-threads/quiz.xml">

<!ENTITY GUI2_intro SYSTEM "c13-GUI2/intro.xml">
<!ENTITY GUI2_s1 SYSTEM "c13-GUI2/s1.xml">
<!ENTITY GUI2_s2 SYSTEM "c13-GUI2/s2.xml">
<!ENTITY GUI2_s3 SYSTEM "c13-GUI2/s3.xml">
<!ENTITY GUI2_s4 SYSTEM "c13-GUI2/s4.xml">
<!ENTITY GUI2_s5 SYSTEM "c13-GUI2/s5.xml">
<!ENTITY GUI2_exercises SYSTEM "c13-GUI2/exercises.xml">
<!ENTITY GUI2_quiz SYSTEM "c13-GUI2/quiz.xml">

=== davidjeck/javanotes9/javanotes9/c1-overview/s3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../javanotes8.dtd" >

<section id="overview.3" title="The Java Virtual Machine">
    
<p><start><big>M</big>achine language consists</start> of very simple
instructions that can be executed directly by the CPU of a computer. Almost all
programs, though, are written in <newword>high-level programming languages</newword> 
such as Java, Python, or C++. A program written in a
high-level language cannot be run directly on any computer. First, it has to be
translated into machine language. This translation can be done by a program
called a <newword>compiler</newword>. A compiler takes a
high-level-language program and translates it into an executable
machine-language program. Once the translation is done, the machine-language
program can be run any number of times, but of course it can only be run on one
type of computer (since each type of computer has its own individual machine
language). If the program is to run on another type of computer it has to be
re-translated, using a different compiler, into the appropriate machine
language.</p>

<p>There is an alternative to compiling a high-level language program. Instead
of using a compiler, which translates the program all at once, you can use an
<newword>interpreter</newword>, which translates it
instruction-by-instruction, as necessary. An interpreter is a program that acts
much like a CPU, with a kind of fetch-and-execute cycle. In order to execute a
program, the interpreter runs in a loop in which it repeatedly reads one
instruction from the program, decides what is necessary to carry out that
instruction, and then performs the appropriate machine-language commands to do
so.</p>

<p>(A compiler is like a human translator who translates an entire book from
one language to another, producing a new book in the second language.
An interpreter is more like a human interpreter who translates a speech at
the United Nations from one language to another at the same time that
the speech is being given.)</p>

<p>One use of interpreters is to execute high-level language programs. For
example, the programming language Lisp is usually executed by an interpreter
rather than a compiler. However, interpreters have another purpose: They can
let you use a machine-language program meant for one type of computer on a
completely different type of computer. For example, one of the original home
computers was the Commodore&nbsp;64 or "C64".  While you might not find an actual
C64, you can find programs that run on other computers&mdash;or even in
a web browser&mdash;that "emulate" one.  Such an emulator can run C64 programs by
acting as an interpreter for the C64 machine language.</p>

<break/>

<p>The designers of Java chose to use a combination of compiling and
interpreting. Programs written in Java are compiled into machine language,
but it is a machine language for a computer that doesn't really exist. This
so-called "virtual" computer is known as the <newword>Java Virtual Machine</newword>,
or JVM.
The machine language for the Java Virtual Machine is called
<newword>Java bytecode</newword>.  There is no reason why Java
bytecode couldn't be used as the machine language of a real computer, rather
than a virtual computer.  But in fact the use of a virtual machine makes possible
one of the main selling points of Java: the fact that it can actually be
used on <b>any</b> computer. All that the computer needs is an interpreter for
Java bytecode. Such an interpreter simulates the JVM in the
same way that a C64 emulator simulates a Commodore&nbsp;64 computer.  (The term JVM is also used 
for the Java bytecode interpreter program that does the simulation, so we say that
a computer needs a JVM in order to run Java programs.  Technically, it would
be more correct to say that the interpreter <i>implements</i> the JVM than
to say that it <i>is</i> a JVM.)</p>

<p>Of course, a different Java bytecode interpreter is needed for each type of
computer, but once a computer has a Java bytecode interpreter, it can run any
Java bytecode program, and the same program can be run on any
computer that has such an interpreter. This is one of the essential features of
Java: the same compiled program can be run on many different types of
computers.</p>

<img height="208" width="530" src="overview-fig3.png" tex="overview-fig3.eps" texscale="0.8" bordered="true"/>

<p>Why, you might wonder, use the intermediate Java bytecode at all? Why not
just distribute the original Java program and let each person compile it into
the machine language of whatever computer they want to run it on? There are
several reasons. First of all, a compiler has to understand Java, a complex
high-level language. The compiler is itself a complex program. A Java bytecode
interpreter, on the other hand, is a relatively small, simple program. This makes
it easy to write a bytecode interpreter for a new type of computer; once that
is done, that computer can run any compiled Java program. It would be much
harder to write a Java compiler for the same computer.</p>

<p>Furthermore, some Java programs are meant to be downloaded over a network.
This leads to obvious security concerns: you don't want to download and run a
program that will damage your computer or your files. The bytecode interpreter
acts as a buffer between you and the program you download. You are really
running the interpreter, which runs the downloaded program indirectly. The
interpreter can protect you from potentially dangerous actions on the part of
that program.</p>

<p>When Java was still a new language, it was criticized for being slow:
Since Java bytecode was executed by an interpreter, it seemed that Java
bytecode programs could never run as quickly as programs compiled into
native machine language (that is, the actual
machine language of the computer on which the program is running).
However, this problem has been largely overcome by the use of <newword>just-in-time
compilers</newword> for executing Java bytecode.  A just-in-time compiler
translates Java bytecode into native machine language.  It does
this while it is executing the program.  Just as for a normal interpreter,
the input to a just-in-time compiler is a Java bytecode program, and its task
is to execute that program.  But as it is executing the program, it also
translates parts of it into machine language.  The translated parts of the
program can then be executed much more quickly than they could be interpreted.
Since a given part of a program is often executed many times as the program
runs, a just-in-time compiler can significantly speed up the overall 
execution time.
</p>

<p>I should note that there is no necessary connection between Java and Java
bytecode. A program written in Java could certainly be compiled into the
machine language of a real computer. And programs written in other languages
can be compiled into Java bytecode. However, the combination of Java
and Java bytecode is platform-independent, secure, and network-compatible
while allowing you to program in a modern high-level object-oriented
language.</p>

<p>In the past few years, it has become fairly common to create new programming
languages, or versions of old languages, that compile into Java bytecode.  The 
compiled bytecode programs can then be executed by a standard JVM.  New languages
that have been developed specifically for programming the JVM include Scala,
Groovy, Clojure, and Processing.  Jython and JRuby are versions of older languages,
Python and Ruby, that target the JVM.  These languages make it possible to
enjoy many of the advantages of the JVM while avoiding some of the technicalities
of the Java language.  In fact, the use of other languages with the JVM has
become important enough that several new features have been added to the
JVM specifically to add better support for some of those languages.  And this
improvement to the JVM has in turn made possible some new features in Java.</p>

<break/>

<p>I should also note that the really hard part of platform-independence is
providing a "Graphical User Interface"&mdash;with windows, buttons, etc.&mdash;that
will work on all the platforms that support Java. You'll see more about this
problem in <localref href="overview.6"/>.</p>

</section>

=== davidjeck/javanotes9/javanotes8/c1-overview/s6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../javanotes8.dtd" >

<section id="overview.6" title="The Modern User Interface">

<p><start><big>W</big>hen computers were first introduced</start>, ordinary
people&mdash;including most programmers&mdash;couldn't get near them. They were
locked up in rooms with white-coated attendants who would take your programs
and data, feed them to the computer, and return the computer's response some
time later. When timesharing&mdash;where the computer switches its attention
rapidly from one person to another&mdash;was invented in the 1960s, it became
possible for several people to interact directly with the computer at the same
time. On a timesharing system, users sit at "terminals" where they type
commands to the computer, and the computer types back its response. Early
personal computers also used typed commands and responses, except that there
was only one person involved at a time. This type of interaction between a user
and a computer is called a <newword>command-line interface</newword>.</p>

<p>Today, of course, most people interact with computers in a completely
different way. They use a <newword>Graphical User Interface</newword>, 
or GUI. The computer draws interface <newword>components</newword> on the
screen. The components include things like windows, scroll bars, menus,
buttons, and icons. Usually, a <newword>mouse</newword> is used to
manipulate such components or, on "touchscreens," your fingers.
Assuming that you have not just been teleported in
from the 1970s, you are no doubt already familiar with the basics of graphical user
interfaces!</p>

<p>A lot of GUI interface components have become fairly standard. That is, they
have similar appearance and behavior on many different computer platforms
including Mac&nbsp;OS, Windows, and Linux. Java programs,
which are supposed to run on many different platforms without modification to
the program, can use all the standard GUI components. They might vary a little in
appearance from platform to platform, but their functionality should be
identical on any computer on which the program runs.</p>

<p>Shown below is an image of a very simple Java program that demonstrates
a few standard GUI interface components.  When the program is run, a window
similar to the picture shown here will open on the computer screen.
There are four components in the window with which the user can interact: 
a button, a checkbox, a text field, and
a pop-up menu. These components are labeled. There are a few other components
in the window. The labels themselves are components (even though you can't
interact with them). The right half of the window is a text area component,
which can display multiple lines of text. A&nbsp;scrollbar component appears
alongside the text area when the number of lines of text becomes larger
than will fit in the text area.  And in fact, in Java terminology, the
whole window is itself considered to be a "component."</p>

<img src="overview-GUIDemo.png" tex="overview-GUIDemo.eps" height="177" width="561" 
    alt="Screenshot from GUIDemo demonstrates some basic GUI components"
    texscale="0.6" bordered="true"/>
    
<np>(If you would like to run this program, the source code, <sourceref href="GUIDemo.java"/>,
is available on line.  For more information on using
this and other examples from this textbook, see <localref href="basics.6"/>.)</np>

<p>Now, Java actually has three complete sets of GUI components. One of these,
the AWT or <newword>Abstract Windowing Toolkit</newword>, was
available in the original version of Java. The second, which is known as
<newword>Swing</newword>, was introduced in Java version 1.2,
and was the standard GUI toolkit for many years.  The third GUI toolkit,
JavaFX, became a standard part of Java in Version&nbsp;8 (but 
but has recently been removed, so that it requires separate installation 
in some versions of Java).  Although
Swing, and even the AWT, can still be used, JavaFX is meant as a more modern
way to write GUI applications.  This textbook covers JavaFX exclusively.
(If you need to learn Swing, you can take a look at the previous version of this book.)
</p>

<p>When a user interacts with GUI components,
"events" are generated.  For example, clicking a push button generates an event, and pressing
a key on the keyboard generates an event.
Each time an
event is generated, a message is sent to the program telling it that the event
has occurred, and the program responds according to its program. In fact, a typical GUI
program consists largely of "event handlers" that tell the program how to respond
to various types of events. In the above example, the program has been programmed
to respond to each event by displaying a message in the text area.
In a more realistic example, the event handlers would have more to do.</p>

<p>The use of the term "message" here is deliberate. Messages, as you saw in
the <localref href="overview.5">previous&nbsp;section</localref>, are sent to objects. In fact, Java
GUI components are implemented as objects. Java includes many predefined
classes that represent various types of GUI components. Some of these classes
are subclasses of others. Here is a diagram showing just a few of the JavaFX GUI classes
and their relationships:</p>

<img width="605" height="272" src="overview-fig5.png" tex="overview-fig5.eps" texscale="0.7"/>

<p>Don't worry about the details for now, but try to get some feel about how
object-oriented programming and inheritance are used here. Note that all the
GUI classes shown here are subclasses, directly or indirectly, of a class called
<classname>Control</classname>, which represents general properties
that are shared by many JavaFX components. In the diagram,
two of the direct subclasses of <classname>Control</classname>
themselves have subclasses. The classes <classname>TextField</classname> and
<classname>TextArea</classname>, which have certain behaviors in common, are grouped
together as subclasses of <classname>TextInputControl</classname>.
Similarly <classname>Button</classname> and <classname>CheckBox</classname>
are subclasses of <classname>ButtonBase</classname>, which represents
properties common to both buttons and checkboxes.  (<classname>ComboBox</classname>,
by the way, is the class that represents pop-up menus.)
</p>

<p>Just from this brief discussion, perhaps you can see how GUI programming can
make effective use of object-oriented design. In fact, GUIs, with their
"visible objects," are probably a major factor contributing to the popularity
of OOP.</p>

<p>Programming with GUI components and events is one of the most interesting
aspects of Java. However, we will spend several chapters on the basics before
returning to this topic in <localref href="GUI1"/>.</p>
    
</section>
