=== davidjeck/javanotes9/javanotes8/javanotes8.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY pi "&#960;">       <!-- these are used by javanotes7.xml but are redefined in javanotes7-tex.xml -->
<!ENTITY Omega "&#937;">
<!ENTITY Theta "&#920;">
<!ENTITY nbsp "&#160;">
<!ENTITY BigOh "O">
<!ENTITY dots "...">
<!ENTITY mdash " -- ">
<!ENTITY leftquote '"'>
<!ENTITY textitlebreak "">
<!ENTITY newcodestyle "red">

<!ENTITY includes SYSTEM "javanotes8-xml-includes.txt">

<!ENTITY % textitem "b|i|u|big|sub|sup|code|br|a|localref|web|tex|sourceref|jarref|ptype|newword|codedef|bnf|newcode|start|classname|atype|prog">
<!ENTITY % simpletext "(#PCDATA|%textitem;)*">
<!ENTITY % text "(p|np|pre|break|img|ul|ol|narrower|centered|imageclear|webdiv|texdiv)*">

<!ELEMENT javanotes (preface?,chapter*,fudgeref*,glossary?,source?)>
<!ELEMENT preface (%text;)>
<!ELEMENT intro (%text;)>

<!ELEMENT chapter (intro,section*,exercises?,quiz?)>
<!ATTLIST chapter 
	id ID #REQUIRED
	title CDATA #REQUIRED
	shorttitle CDATA #IMPLIED>

<!ELEMENT section (%text;,subsection*,endchapter?)>
<!ATTLIST section 
	id ID #REQUIRED
	title CDATA #REQUIRED
	shorttitle CDATA #IMPLIED>

<!ELEMENT subsection (%text;)>
<!ATTLIST subsection 
	id ID #REQUIRED
	title CDATA #REQUIRED
	shorttitle CDATA #IMPLIED>
<!ELEMENT endchapter EMPTY>

<!ELEMENT source (%text;,subsection*)>

<!ELEMENT glossary (gitem*)>
<!ELEMENT gitem %simpletext;>
<!ATTLIST gitem
   term CDATA #REQUIRED>

<!ELEMENT fudgeref EMPTY>
<!ATTLIST fudgeref
   id ID #REQUIRED
   text CDATA #REQUIRED>

<!ELEMENT exercises (exercise*)>
<!ELEMENT exercise (exercise-question,exercise-discuss,exercise-code)>
<!ATTLIST exercise
    id ID #IMPLIED>
<!ELEMENT exercise-question %text;>
<!ELEMENT exercise-discuss %text;>
<!ELEMENT exercise-code %text;>

<!ELEMENT quiz (question*)>
<!ELEMENT question (ques,ans)>
<!ELEMENT ques %text;>
<!ELEMENT ans %text;>

<!ELEMENT pre %simpletext;>
<!ATTLIST pre
	xml:space CDATA #FIXED "preserve">
	
<!ELEMENT prog %simpletext;>
<!ATTLIST prog
	xml:space CDATA #FIXED "preserve"
	name CDATA #REQUIRED>

<!ELEMENT p %simpletext;>
<!ATTLIST p 
    align CDATA #IMPLIED>
<!ELEMENT np %simpletext;>

<!ELEMENT narrower %text;>
<!ATTLIST narrower
   margin CDATA #IMPLIED>

<!ELEMENT centered %text;>

<!ELEMENT localref (#PCDATA)>
<!ATTLIST localref
    href CDATA #REQUIRED>

<!ELEMENT sourceref (#PCDATA)>
<!ATTLIST sourceref
    href CDATA #REQUIRED
    chapter CDATA #IMPLIED>

<!ELEMENT jarref (#PCDATA)>
<!ATTLIST jarref
    href CDATA #REQUIRED>

<!ELEMENT a (#PCDATA)>
<!ATTLIST a
    href CDATA #REQUIRED>

<!ELEMENT img EMPTY>
<!ATTLIST img
    src CDATA #IMPLIED
    alt CDATA #IMPLIED
    width CDATA #IMPLIED
    height CDATA #IMPLIED
    bordered CDATA #IMPLIED
    align CDATA #IMPLIED
    tex CDATA #IMPLIED
    texscale CDATA #IMPLIED>
    
<!ELEMENT ul (li*)>
<!ELEMENT ol (li*)>
<!ELEMENT li %simpletext;>

<!ELEMENT br EMPTY>
<!ELEMENT break EMPTY>
<!ELEMENT imageclear EMPTY> <!-- adds a "br clear=all" in the web version -->
<!ELEMENT i %simpletext;>
<!ELEMENT b %simpletext;>
<!ELEMENT u %simpletext;>
<!ELEMENT big %simpletext;>
<!ELEMENT start %simpletext;>
<!ELEMENT sup %simpletext;>
<!ELEMENT sub %simpletext;>
<!ELEMENT code %simpletext;>
<!ELEMENT newcode %simpletext;>
<!ELEMENT web %simpletext;>   <!-- appears only in web version -->
<!ELEMENT tex %simpletext;>   <!-- appears only in tex version -->
<!ELEMENT ptype %simpletext;>   <!-- primitive type -->
<!ELEMENT bnf %simpletext;>
<!ELEMENT classname (#PCDATA)>
<!ELEMENT atype (#PCDATA)>       <!-- array type -->
<!ELEMENT newword %simpletext;>
<!ELEMENT codedef %simpletext;>
<!ELEMENT webdiv %text;>   <!-- appears only in web version -->
<!ELEMENT texdiv %text;>   <!-- appears only in tex version -->

<!ENTITY source SYSTEM "source.xml">
<!ENTITY glossary SYSTEM "glossary.xml">
<!ENTITY preface SYSTEM "preface.xml">

<!ENTITY overview_intro SYSTEM "c1-overview/intro.xml">
<!ENTITY overview_s1 SYSTEM "c1-overview/s1.xml">
<!ENTITY overview_s2 SYSTEM "c1-overview/s2.xml">
<!ENTITY overview_s3 SYSTEM "c1-overview/s3.xml">
<!ENTITY overview_s4 SYSTEM "c1-overview/s4.xml">
<!ENTITY overview_s5 SYSTEM "c1-overview/s5.xml">
<!ENTITY overview_s6 SYSTEM "c1-overview/s6.xml">
<!ENTITY overview_s7 SYSTEM "c1-overview/s7.xml">
<!ENTITY overview_quiz SYSTEM "c1-overview/quiz.xml">

<!ENTITY basics_intro SYSTEM "c2-basics/intro.xml">
<!ENTITY basics_s1 SYSTEM "c2-basics/s1.xml">
<!ENTITY basics_s2 SYSTEM "c2-basics/s2.xml">
<!ENTITY basics_s3 SYSTEM "c2-basics/s3.xml">
<!ENTITY basics_s4 SYSTEM "c2-basics/s4.xml">
<!ENTITY basics_s5 SYSTEM "c2-basics/s5.xml">
<!ENTITY basics_s6 SYSTEM "c2-basics/s6.xml">
<!ENTITY basics_exercises SYSTEM "c2-basics/exercises.xml">
<!ENTITY basics_quiz SYSTEM "c2-basics/quiz.xml">

<!ENTITY control_intro SYSTEM "c3-control/intro.xml">
<!ENTITY control_s1 SYSTEM "c3-control/s1.xml">
<!ENTITY control_s2 SYSTEM "c3-control/s2.xml">
<!ENTITY control_s3 SYSTEM "c3-control/s3.xml">
<!ENTITY control_s4 SYSTEM "c3-control/s4.xml">
<!ENTITY control_s5 SYSTEM "c3-control/s5.xml">
<!ENTITY control_s6 SYSTEM "c3-control/s6.xml">
<!ENTITY control_s7 SYSTEM "c3-control/s7.xml">
<!ENTITY control_s7a SYSTEM "c3-control/s7a.xml">
<!ENTITY control_s8 SYSTEM "c3-control/s8.xml">
<!ENTITY control_exercises SYSTEM "c3-control/exercises.xml">
<!ENTITY control_quiz SYSTEM "c3-control/quiz.xml">

<!ENTITY subroutines_intro SYSTEM "c4-subroutines/intro.xml">
<!ENTITY subroutines_s1 SYSTEM "c4-subroutines/s1.xml">
<!ENTITY subroutines_s2 SYSTEM "c4-subroutines/s2.xml">
<!ENTITY subroutines_s3 SYSTEM "c4-subroutines/s3.xml">
<!ENTITY subroutines_s4 SYSTEM "c4-subroutines/s4.xml">
<!ENTITY subroutines_s4a SYSTEM "c4-subroutines/s4a.xml">
<!ENTITY subroutines_s5 SYSTEM "c4-subroutines/s5.xml">
<!ENTITY subroutines_s6 SYSTEM "c4-subroutines/s6.xml">
<!ENTITY subroutines_s7 SYSTEM "c4-subroutines/s7.xml">
<!ENTITY subroutines_exercises SYSTEM "c4-subroutines/exercises.xml">
<!ENTITY subroutines_quiz SYSTEM "c4-subroutines/quiz.xml">

<!ENTITY OOP_intro SYSTEM "c5-OOP/intro.xml">
<!ENTITY OOP_s1 SYSTEM "c5-OOP/s1.xml">
<!ENTITY OOP_s2 SYSTEM "c5-OOP/s2.xml">
<!ENTITY OOP_s3 SYSTEM "c5-OOP/s3.xml">
<!ENTITY OOP_s4 SYSTEM "c5-OOP/s4.xml">
<!ENTITY OOP_s5 SYSTEM "c5-OOP/s5.xml">
<!ENTITY OOP_s6 SYSTEM "c5-OOP/s6.xml">
<!ENTITY OOP_s7 SYSTEM "c5-OOP/s7.xml">
<!ENTITY OOP_s8 SYSTEM "c5-OOP/s8.xml">
<!ENTITY OOP_exercises SYSTEM "c5-OOP/exercises.xml">
<!ENTITY OOP_quiz SYSTEM "c5-OOP/quiz.xml">

<!ENTITY GUI1_intro SYSTEM "c6-GUI1/intro.xml">
<!ENTITY GUI1_s1 SYSTEM "c6-GUI1/s1.xml"> 
<!ENTITY GUI1_s2 SYSTEM "c6-GUI1/s2.xml"> 
<!ENTITY GUI1_s3 SYSTEM "c6-GUI1/s3.xml">
<!ENTITY GUI1_s4 SYSTEM "c6-GUI1/s4.xml">
<!ENTITY GUI1_s5 SYSTEM "c6-GUI1/s5.xml">
<!ENTITY GUI1_s6 SYSTEM "c6-GUI1/s6.xml">
<!ENTITY GUI1_exercises SYSTEM "c6-GUI1/exercises.xml">
<!ENTITY GUI1_quiz SYSTEM "c6-GUI1/quiz.xml">

<!ENTITY arrays_intro SYSTEM "c7-arrays/intro.xml">
<!ENTITY arrays_s1 SYSTEM "c7-arrays/s1.xml">
<!ENTITY arrays_s2 SYSTEM "c7-arrays/s2.xml">
<!ENTITY arrays_s3 SYSTEM "c7-arrays/s3.xml">
<!ENTITY arrays_s4 SYSTEM "c7-arrays/s4.xml">
<!ENTITY arrays_s5 SYSTEM "c7-arrays/s5.xml">
<!ENTITY arrays_exercises SYSTEM "c7-arrays/exercises.xml">
<!ENTITY arrays_quiz SYSTEM "c7-arrays/quiz.xml">

<!ENTITY robustness_intro SYSTEM "c8-robustness/intro.xml">
<!ENTITY robustness_s1 SYSTEM "c8-robustness/s1.xml">
<!ENTITY robustness_s2 SYSTEM "c8-robustness/s2.xml">
<!ENTITY robustness_s3 SYSTEM "c8-robustness/s3.xml">
<!ENTITY robustness_s4 SYSTEM "c8-robustness/s4.xml">
<!ENTITY robustness_s5 SYSTEM "c8-robustness/s5.xml">
<!ENTITY robustness_exercises SYSTEM "c8-robustness/exercises.xml">
<!ENTITY robustness_quiz SYSTEM "c8-robustness/quiz.xml">

<!ENTITY recursion_intro SYSTEM "c9-recursion/intro.xml">
<!ENTITY recursion_s1 SYSTEM "c9-recursion/s1.xml">
<!ENTITY recursion_s2 SYSTEM "c9-recursion/s2.xml">
<!ENTITY recursion_s3 SYSTEM "c9-recursion/s3.xml">
<!ENTITY recursion_s4 SYSTEM "c9-recursion/s4.xml">
<!ENTITY recursion_s5 SYSTEM "c9-recursion/s5.xml">
<!ENTITY recursion_exercises SYSTEM "c9-recursion/exercises.xml">
<!ENTITY recursion_quiz SYSTEM "c9-recursion/quiz.xml">

<!ENTITY generics_intro SYSTEM "c10-generics/intro.xml">
<!ENTITY generics_s1 SYSTEM "c10-generics/s1.xml">
<!ENTITY generics_s2 SYSTEM "c10-generics/s2.xml">
<!ENTITY generics_s3 SYSTEM "c10-generics/s3.xml">
<!ENTITY generics_s4 SYSTEM "c10-generics/s4.xml">
<!ENTITY generics_s5 SYSTEM "c10-generics/s5.xml">
<!ENTITY generics_s6 SYSTEM "c10-generics/s6.xml">
<!ENTITY generics_exercises SYSTEM "c10-generics/exercises.xml">
<!ENTITY generics_quiz SYSTEM "c10-generics/quiz.xml">

<!ENTITY IO_intro SYSTEM "c11-IO/intro.xml">
<!ENTITY IO_s1 SYSTEM "c11-IO/s1.xml">
<!ENTITY IO_s2 SYSTEM "c11-IO/s2.xml">
<!ENTITY IO_s3 SYSTEM "c11-IO/s3.xml">
<!ENTITY IO_s4 SYSTEM "c11-IO/s4.xml">
<!ENTITY IO_s5 SYSTEM "c11-IO/s5.xml">
<!ENTITY IO_exercises SYSTEM "c11-IO/exercises.xml">
<!ENTITY IO_quiz SYSTEM "c11-IO/quiz.xml">

<!ENTITY threads_intro SYSTEM "c12-threads/intro.xml">
<!ENTITY threads_s1 SYSTEM "c12-threads/s1.xml">
<!ENTITY threads_s2 SYSTEM "c12-threads/s2.xml">
<!ENTITY threads_s3 SYSTEM "c12-threads/s3.xml">
<!ENTITY threads_s4 SYSTEM "c12-threads/s4.xml">
<!ENTITY threads_s5 SYSTEM "c12-threads/s5.xml">
<!ENTITY threads_exercises SYSTEM "c12-threads/exercises.xml">
<!ENTITY threads_quiz SYSTEM "c12-threads/quiz.xml">

<!ENTITY GUI2_intro SYSTEM "c13-GUI2/intro.xml">
<!ENTITY GUI2_s1 SYSTEM "c13-GUI2/s1.xml">
<!ENTITY GUI2_s2 SYSTEM "c13-GUI2/s2.xml">
<!ENTITY GUI2_s3 SYSTEM "c13-GUI2/s3.xml">
<!ENTITY GUI2_s4 SYSTEM "c13-GUI2/s4.xml">
<!ENTITY GUI2_s5 SYSTEM "c13-GUI2/s5.xml">
<!ENTITY GUI2_exercises SYSTEM "c13-GUI2/exercises.xml">
<!ENTITY GUI2_quiz SYSTEM "c13-GUI2/quiz.xml">

=== davidjeck/javanotes9/javanotes9/c1-overview/s4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../javanotes8.dtd" >

<section id="overview.4" title="Fundamental Building Blocks of Programs" shorttitle="Building Blocks of Programs">
    
<p><start><big>T</big>here are two basic aspects</start> of programming: data
and instructions. To work with data, you need to understand <newword>variables</newword> 
and <newword>types</newword>; to work with
instructions, you need to understand <newword>control structures</newword> 
and <newword>subroutines</newword>. You'll spend a
large part of the course becoming familiar with these concepts.</p>

<p>A <newword>variable</newword> is just a memory location (or
several consecutive locations treated as a unit) that has been given a name so that it can
be easily referred to and used in a program. The programmer only has to worry
about the name; it is the compiler's responsibility to keep track of the memory
location. As a programmer, you just need to keep in mind that the name refers to a
kind of "box" in memory that can hold data, even though you don't have
to know where in memory that box is located.</p>

<p>In Java and in many other programming languages, a variable has a <newword>type</newword>
that indicates what sort of data it can hold. One type of
variable might hold integers&mdash;whole numbers such as 3, -7, and 0&mdash;while
another holds floating point numbers&mdash;numbers with decimal points such as
3.14, -2.7, or 17.0. (Yes, the computer does make a distinction between the
integer 17 and the floating-point number 17.0; they actually look quite
different inside the computer.) There could also be types for individual
characters ('A', ';', etc.), strings ("Hello", "A string can include many
characters", etc.), and less common types such as dates, colors, sounds, or any
other kind of data that a program might need to store.</p>

<p>Programming languages always have commands for getting data into and out of
variables and for doing computations with data. For example, the following
"assignment statement," which might appear in a Java program, tells the
computer to take the number stored in the variable named "principal", multiply
that number by 0.07, and then store the result in the variable named
"interest":</p>

<pre>interest = principal * 0.07;</pre>

<np>There are also "input commands" for getting data from the user or from files
on the computer's disks, and there are "output commands" for sending data in the other
direction.</np>

<p>These basic commands&mdash;for moving data from place to place and for
performing computations&mdash;are the building blocks for all programs. These
building blocks are combined into complex programs using control structures and
subroutines.</p>

<break/>

<p>A program is a sequence of instructions. In the ordinary "flow of control,"
the computer executes the instructions in the sequence in which they occur in the program,
one after the other. However, this is obviously very limited: the computer
would soon run out of instructions to execute. <newword>Control structures</newword> 
are special instructions that can change the flow of control.
There are two basic types of control structure: <newword>loops</newword>,
which allow a sequence of instructions to be repeated
over and over, and <newword>branches</newword>, which allow the
computer to decide between two or more different courses of action by testing
conditions that occur as the program is running.</p>

<p>For example, it might be that if the value of the variable "principal" is
greater than 10000, then the "interest" should be computed by multiplying the
principal by 0.05; if not, then the interest should be computed by multiplying
the principal by 0.04. A program needs some way of expressing this type of
decision. In Java, it could be expressed using the following "if
statement":</p>

<pre>if (principal &gt; 10000)
    interest = principal * 0.05;
else
    interest = principal * 0.04;</pre>

<np>(Don't worry about the details for now. Just remember that the computer can
test a condition and decide what to do next on the basis of that test.)</np>

<p>Loops are used when the same task has to be performed more than once. For
example, if you want to print out a mailing label for each name on a mailing
list, you might say, "Get the first name and address and print the label; get
the second name and address and print the label; get the third name and address
and print the label&dots;" But this quickly becomes ridiculous&mdash;and might not
work at all if you don't know in advance how many names there are. What you
would like to say is something like "While there are more names to process, get
the next name and address, and print the label." A loop can be used in a
program to express such repetition.</p>

<break/>

<p>Large programs are so complex that it would be almost impossible to write
them if there were not some way to break them up into manageable "chunks."
Subroutines provide one way to do this. A <newword>subroutine</newword> 
consists of the instructions for performing some
task, grouped together as a unit and given a name. That name can then be used
as a substitute for the whole set of instructions. For example, suppose that
one of the tasks that your program needs to perform is to draw a house on the
screen. You can take the necessary instructions, make them into a subroutine,
and give that subroutine some appropriate name&mdash;say, "drawHouse()". Then
anyplace in your program where you need to draw a house, you can do so with the
single command:</p>

<pre>drawHouse();</pre>

<np>This will have the same effect as repeating all the house-drawing
instructions in each place.</np>

<p>The advantage here is not just that you save typing. Organizing your program
into subroutines also helps you organize your thinking and your program design
effort. While writing the house-drawing subroutine, you can concentrate on the
problem of drawing a house without worrying for the moment about the rest of
the program. And once the subroutine is written, you can forget about the
details of drawing houses&mdash;that problem is solved, since you have a
subroutine to do it for you. A subroutine becomes just like a built-in part of
the language which you can use without thinking about the details of what goes
on "inside" the subroutine.</p>

<break/>

<p>Variables, types, loops, branches, and subroutines are the basis of what
might be called "traditional programming." However, as programs become larger,
additional structure is needed to help deal with their complexity. One of the
most effective tools that has been found is object-oriented programming, which
is discussed in the next section.</p>

</section>

=== davidjeck/javanotes9/javanotes8/c2-basics/intro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE intro SYSTEM "../javanotes8.dtd" >

<intro>
   <p><start><big>O</big>n a basic level</start> (the level of machine language), a
   computer can perform only very simple operations. A computer performs complex
   tasks by stringing together large numbers of such operations. Such tasks must
   be "scripted" in complete and perfect detail by programs. Creating complex
   programs will never be really easy, but the difficulty can be handled to some
   extent by giving the program a clear overall <newword>structure</newword>.
   The design of the overall structure of a program is
   what I call "programming in the large."</p>
   <p>Programming in the small, which is sometimes called <newword>coding</newword>, 
   would then refer to filling in the details of that
   design. The details are the explicit, step-by-step instructions for performing
   fairly small-scale tasks. When you do coding, you are working "close to
   the machine," with some of the same concepts that you might use in machine
   language: memory locations, arithmetic operations, loops and branches. In a
   high-level language such as Java, you get to work with these concepts on a
   level several steps above machine language. However, you still have to worry
   about getting all the details exactly right.</p>
   <p>This chapter and the next examine the facilities for programming in the
   small in the Java programming language. Don't be misled by the term
   "programming in the small" into thinking that this material is easy or
   unimportant. This material is an essential foundation for all types of
   programming. If you don't understand it, you can't write programs, no matter
   how good you get at designing their large-scale structure.</p>
   <p>The <localref href="basics.6">last section</localref> of this chapter discusses <newword>programming environments</newword>.
   That section contains information about how to compile and run Java programs,
   and you should take a look at it before trying to write and use your own programs
   or trying to use the sample programs in this book.</p>
</intro>

=== davidjeck/javanotes9/javanotes9/c6-GUI1/intro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE intro SYSTEM "../javanotes8.dtd" >

<intro>
<p><start><big>C</big>omputer users today expect</start> to interact
with their computers using a graphical user interface (GUI), and
Java can be used to write sophisticated GUI programs.</p>
   
<p>GUI programs
differ from traditional "straight-through" programs that you have 
encountered in the first few chapters of this book.  One big difference is
that GUI programs are <newword>event-driven</newword>. That is, user actions such as
clicking on a button or pressing a key on the keyboard generate events, and the
program must respond to these events as they occur.</p>

<p>Event-driven programming builds on all the skills you have learned in the
first five chapters of this text. You need to be able to write the methods
that respond to events. Inside those methods, you are doing the kind of
programming-in-the-small that was covered in <localref href="basics"/>
and <localref href="control"/>.
And of course, objects are everywhere in GUI programming.  
Events are objects. Colors and fonts are objects.  GUI components such as buttons and
menus are objects.  Events are handled by instance methods contained in objects. 
In Java, GUI programming is object-oriented programming.  The purpose of this chapter is, as
much as anything, to give you some experience with a large-scale object-oriented API.</p>

<p>Java has had several "toolkits" for building GUI program.  This textbook
uses <newword>JavaFX</newword> as its toolkit.  The previous version used
the Swing GUI toolkit, and if you are interested in learning Swing rather
than JavaFX, you should consult Chapter&nbsp;6 and Chapter&nbsp;13 in
that version, which is still available at
<a href="http://math.hws.edu/javanotes7">http://math.hws.edu/javanotes7</a>.</p>

<p>This chapter is just an introduction to JavaFX, but it covers the
essential features of GUI programming in enough detail to write some
interesting programs.  The discussion of JavaFX will continue in <localref href="GUI2"/> 
with more details and with more advanced techniques, but complete coverage
of JavaFX would require an entire book of its own.</p>

<p>Note that JavaFX is no longer being distributed as part of the Java
Development Kit.  For information about how to obtain JavaFX and how to
compile and run programs that use it, see <localref href="basics.6"/>.</p>

</intro>
